//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Editor.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_SCINTILLA_DEFAULT_PRINT_HEADER 129
#define IDR_EditorTYPE                  130
#define IDS_SCINTILLA_DEFAULT_PRINT_FOOTER 131
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_EDIT_MENU                   306
#define IDB_SCENELARGE                  310
#define ID_RESOURCE_MANAGER             310
#define ID_LAYER1_DEL_NORMAL_HEIGHT     310
#define IDB_SCENESMALL                  311
#define ID_SCENE_RESOURCE               311
#define ID_LAYER2_DEL_NORMAL_HEIGHT     311
#define IDD_NEWSCENE                    312
#define ID_TERRAIN_EDIT_WND             312
#define ID_LAYER3_DEL_NORMAL_HEIGHT     312
#define IDB_SCENE_RESOURCE_TREE         313
#define ID_PROPERTY_WND                 313
#define ID_LAYER4_DEL_NORMAL_HEIGHT     313
#define IDB_RESOURCE_MANAGER            314
#define IDB_RESOURCE_MANAGER_TREE       314
#define ID_LAYER5_DEL_NORMAL_HEIGHT     314
#define IDR_RESOURCE_PREVIEW            315
#define ID_RESOURCE_PREVIEW             315
#define ID_MESSAGE_LIST                 315
#define ID_SIZE_SLIDER                  316
#define IDB_DOCKING_PANE                317
#define ID_POWER_SLIDER                 317
#define ID_MISC_EDIT_TAB                318
#define ID_MISC_EDIT_WND                319
#define IDD_TERRAIN_EDIT                319
#define ID_CAMERA_WND                   320
#define IDD_TEXTURE_PREVIEW             320
#define ID_RESOURCE_MANAGER_TREE        321
#define ID_SCENE_RESOURCE_TREE          322
#define IDB_DOCKING_WINDOW              322
#define IDD_NEW_SCENE                   323
#define ID_BRUSH_MENU                   324
#define IDC_PLACE                       324
#define IDR_OBJECT_EDIT                 325
#define IDD_SCINTILLA_FINDDLGORD        325
#define IDD_SCINTILLA_REPLACEDLGORD     326
#define JECT_EDIT                       327
#define IDD_MATERIAL_PREVIEW            327
#define IDB_BITMAP1                     328
#define IDB_OBJECT_EDIT                 328
#define IDD_NEW_LIGHT                   329
#define ID_LOAD_DIFFUSESPECULAR         332
#define IDD_SCRIPT_EDITOR               332
#define ID_LOAD_NORMALHEIGHT            333
#define IDD_SCRIPT_EDITOR_MODIFY        333
#define ID_LAYER1                       334
#define IDR_MATERIAL                    334
#define ID_LAYER1_LOAD_DIFFUSE_SPECULAR 335
#define IDD_OGRE_XML_CONVERTER          335
#define ID_LAYER1_LOAD_NORMAL_HEIGHT    336
#define IDD_IMAGE_COMBINATOR            336
#define ID_LAYER1_ADD_LAYER_PREV        337
#define ID_LAYER1_DEL_LAYER             338
#define ID_LAYER2                       339
#define ID_LAYER2_LOAD_DIFFUSE_SPECULAR 340
#define ID_LAYER2_LOAD_NORMAL_HEIGHT    341
#define ID_LAYER2_ADD_LAYER_PREV        342
#define ID_LAYER2_DEL_LAYER             343
#define ID_LAYER1_ADD_LAYER_NEXT        344
#define ID_LAYER2_ADD_LAYER_NEXT        345
#define ID_LAYER3                       346
#define ID_LAYER3_ADD_LAYER_PREV        347
#define ID_LAYER3_ADD_LAYER_NEXT        348
#define ID_LAYER3_DEL_LAYER             349
#define ID_LAYER3_LOAD_DIFFUSE_SPECULAR 350
#define ID_LAYER3_LOAD_NORMAL_HEIGHT    351
#define ID_LAYER4                       352
#define ID_LAYER4_ADD_LAYER_PREV        353
#define ID_LAYER4_ADD_LAYER_NEXT        354
#define ID_LAYER4_DEL_LAYER             355
#define ID_LAYER4_LOAD_DIFFUSE_SPECULAR 356
#define ID_LAYER4_LOAD_NORMAL_HEIGHT    357
#define ID_LAYER5                       358
#define ID_LAYER5_ADD_LAYER_PREV        359
#define ID_LAYER5_ADD_LAYER_NEXT        360
#define ID_LAYER5_DEL_LAYER             361
#define ID_LAYER5_LOAD_DIFFUSE_SPECULAR 362
#define ID_LAYER5_LOAD_NORMAL_HEIGHT    363
#define ID_TEXTURE_SLIDER               364
#define ID_OBJECT_EDIT_TOOLBAR          365
#define ID_TEXTURE_PREVIEW              366
#define IDC_EDIT1                       1001
#define IDC_BUTTON1                     1002
#define IDC_PROPLIST_FRAME              1003
#define IDC_CHECK1                      1003
#define IDC_CHECK2                      1004
#define IDC_CHECK3                      1005
#define IDC_RADIO1                      1006
#define IDC_RADIO2                      1007
#define IDC_BUTTON2                     1008
#define IDC_BUTTON3                     1009
#define IDC_BUTTON4                     1010
#define IDC_BUTTON5                     1011
#define IDC_EDIT2                       1012
#define IDC_REGULAR_EXPRESSION          1013
#define IDC_MATERIAL_FRAME              1015
#define IDC_MFCBUTTON1                  1018
#define IDC_ADD_MATERIAL                1018
#define IDC_MFCBUTTON2                  1019
#define IDC_MFCBUTTON3                  1020
#define IDC_APPLY_MATERIAL              1020
#define IDC_LIST2                       1021
#define IDC_SCRIPTLIST                  1021
#define IDC_LIGHTS                      1021
#define IDC_LIST3                       1022
#define IDC_MATERIAL_LIST               1022
#define IDC_UPDATE_LIGHT                1030
#define IDC_EDIT_MATERIAL               1031
#define IDC_MESH_LIST                   1032
#define IDC_ANIM_LIST                   1032
#define IDC_LIST1                       1033
#define IDC_COMPOSITOR_LIST             1033
#define IDC_SCRIPT                      1033
#define IDC_EDIT_COMPOSITOR             1034
#define IDC_EDIT_PROGRAM                1034
#define IDC_APPLY_COMPOSITOR            1035
#define IDC_APPLY_PROGRAM               1035
#define IDC_CURRENT_COMPOSITORS         1036
#define IDC_ADD_COMPOSITOR              1037
#define IDC_DEL_COMPOSITOR              1038
#define IDC_ENABLE_COMPOSITOR           1039
#define IDC_LOAD_ACTIONS                1039
#define IDC_DISABLE_COMPOSITOR          1040
#define IDC_ACTIONS                     1040
#define IDC_ADD_TO_SCRIPT               1041
#define IDC_ACTION_TEXT                 1042
#define IDC_FRAME                       1043
#define IDC_NUM                         1044
#define IDC_PREV                        1045
#define IDC_NEXT                        1046
#define IDC_STATIC1                     1047
#define IDC_STATIC2                     1048
#define IDC_STATIC3                     1049
#define IDC_MIN                         1050
#define IDC_MAX                         1051
#define IDC_VALUE                       1052
#define IDC_TRUE                        1053
#define IDC_FALSE                       1054
#define IDC_CHOICE                      1055
#define IDC_TEXT                        1056
#define IDC_INSERT_TO_SCRIPT            1057
#define IDC_SAVE_SCRIPT                 1058
#define IDC_LOAD_SCRIPT                 1059
#define IDC_NEW_SCRIPT                  1060
#define IDC_DELETE                      1061
#define IDC_EDIT                        1062
#define IDC_MOVE_UP                     1063
#define IDC_MOVE_DOWN                   1064
#define IDC_CLEAR_MATERIAL              1075
#define IDC_ADD_LIGHT                   1080
#define IDC_DISABLE_LIGHT               1081
#define IDC_DEL_LIGHT                   1081
#define IDC_QUAD                        1082
#define IDC_XML_TO_BINARY               1083
#define IDC_BINARY_TO_XML               1084
#define IDC_INPUT_PATH                  1085
#define IDC_EDIT3                       1086
#define IDC_OUTPUT_PATH                 1086
#define IDC_ARGS                        1087
#define IDC_GET_INPUT_PATH              1088
#define IDC_GET_OUTPUT_PATH             1089
#define IDC_EDIT4                       1090
#define IDC_EDIT5                       1091
#define IDC_EDIT6                       1092
#define IDC_SAVE_NORMAL_HEIGHT          1093
#define IDC_BUTTON7                     1094
#define IDC_GENERATE                    1094
#define IDC_LOAD_DIFFUSE                1095
#define IDC_LOAD_SPECULAR               1096
#define IDC_SAVE_DIFFUSE_SPECULAR       1097
#define IDC_LOAD_NORMAL                 1098
#define IDC_LOAD_HEIGHT                 1099
#define ID_BRUSH_BAR                    10000
#define ID_LOAD_BRUSH                   10001
#define ID_CLEAR_BRUSH                  10002
#define ID_RESIZE_BRUSH                 10003
#define ID_TEXTURE_BAR                  10010
#define ID_LOAD_TEXTURE                 10011
#define ID_CLEAR_TEXTURE                10012
#define ID_RESIZE_TEXTURE               10013
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SHOW_GRID                    32774
#define ID_TRANS_OBJECT                 32775
#define ID_SCALE_OBJECT                 32776
#define ID_ROTATE_OBJECT                32777
#define ID_DEL_OBJECT                   32778
#define ID_SELECT_TERRAIN               32779
#define ID_DEFORM_TERRAIN               32780
#define ID_BLEND_TERRAIN                32781
#define ID_LIQUID_EDIT                  32784
#define ID_ADD_LIGHT                    32786
#define ID_OBJECT_PASTE                 32789
#define ID_SHOW_DEBUG_OVERLAY           32790
#define ID_NEW_GAME                     32791
#define ID_SCRIPT_EDITOR                32793
#define ID_ANIM_LIST                    32794
#define ID_CLEAR_LOG                    32796
#define ID_XML_CONVERTER                32799
#define ID_SAVE_SCENE                   32801
#define ID_OPEN_SCENE                   32802
#define ID_GAME_MODE                    32805
#define ID_NEW_SCENE                    32806
#define ID_32808                        32808
#define ID_IMAGE_COMBINATOR             32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_DEFERRED_SHADING             32812
#define ID_SSAO                         32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        337
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           316
#endif
#endif
